function [] = report(chip, system)
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here
import mlreportgen.dom.*;
d = Document('report','pdf');
text ='Test Report File';
%     system.layer.N,...
%     system.hsp.Xsize,...
%     system.hsp.Ysize,...
%     system.hsp.Xgrid,...
%     system.hsp.Ygrid,...
%     system.pack.Xsize,...
%     system.pack.Ysize,...
%     system.pack.Xgrid,...
%     system.pack.Ygrid,...
%     system.chip.Xgrid,...
%     system.chip.Ygrid ];
p = Paragraph(text);
append (d,p);
tab = struct2table(chip);
% append (d, );
writetable(tab, d);
close(d)
end

